### ISSUE TITLE
Add table name to Velocity Context

### ISSUE THREAD

**Issue by tuzzmaniandevil** [panedrone/sqldalmaker#1]
Can you please add the table name to the context?

This is to add the `@Table(name = "ACCS_BALANCE")` to the DTO class.

**Comment by panedrone** [comment]
Hello, please update to v.1.145 and try to do the following:

[image: image.png]
[image: image.png]


[image: image.png]
[image: image.png]

[image: image.png]

[image: image.png]
[image: image.png]




вс, 13 сент. 2020 г. в 05:06, Wesley <notifications@github.com>:

**Comment by panedrone** [comment]
JDA is not planned
